spring.application.name=user-auth-service

server.port=8081

jwt.secret=${JWT_SECRET_KEY}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

logging.level.web=INFO

management.endpoints.web.exposure.include=health,metrics
